### ISSUE TITLE
cycle to renderman

### ISSUE THREAD

**Issue by deboi238** [prman-pixar/RenderManForBlender#658] opened 2022-09-09 01:53 UTC
i was wondering how to convert the cycle shades/node to renderman since most of my projects/models is made with cycle

**Comment by prman-pixar** [comment] 2022-09-09 16:14
@deboi238 if you look in the addon preferences, there is a setting called Convert Cycles Nodes. Turning this on will add buttons to the material panel to convert the current or all materials in the scene.

HOWEVER, this setting is experimental and most likely will not work in all cases. Also, the converted material is also most likely not the most efficient. It is best to recreate the material from scratch.

**Comment by deboi238** [comment] 2022-09-12 02:58
> @deboi238 if you look in the addon preferences, there is a setting called Convert Cycles Nodes. Turning this on will add buttons to the material panel to convert the current or all materials in the scene.
> 
> HOWEVER, this setting is experimental and most likely will not work in all cases. Also, the converted material is also most likely not the most efficient. It is best to recreate the material from scratch.

yea your right, i tried converting but it gives me errors

**Comment by prman-pixar** [comment] 2022-09-12 15:20
As I said, we officially support converting cycles nodes, but I would be interested to know what the errors you are getting. Can you provide a .blend file that I can look at?

**Comment by deboi238** [comment] 2022-09-13 00:12
Error: Python: Traceback (most recent call last):
  File "C:\Users\deboi\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\RenderManForBlender\rman_operators\rman_operators_nodetree.py", line 46, in execute
    if not ob.cycles_visibility.camera:
AttributeError: 'Object' object has no attribute 'cycles_visibility'

location: <unknown location>:-1

**i cant send the file since it is about 84 mb big**

**Comment by joluga** [comment] 2022-09-14 06:01
> Error: Python: Traceback (most recent call last): File "C:\Users\deboi\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\RenderManForBlender\rman_operators\rman_operators_nodetree.py", line 46, in execute if not ob.cycles_visibility.camera: AttributeError: 'Object' object has no attribute 'cycles_visibility'

Does Renderman works in Blender 3.x?

**Comment by prman-pixar** [comment] 2022-09-14 20:13
@deboi238 I've committed a fix you want to try it (in the dev branch).

**Comment by deboi238** [comment] 2022-09-15 00:45
thanks, it works, now almost all my models works now

**Comment by deboi238** [comment] 2022-09-16 02:11
got new error while converting cycle to renderman

Python: Traceback (most recent call last):
  File "C:\Users\de boi\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\RenderManForBlender-dev\rman_bl_nodes\rman_bl_nodes_shaders.py", line 713, in update
    if link.from_socket.renderman_type != link.to_socket.renderman_type:
AttributeError: 'NodeSocketColor' object has no attribute 'renderman_type'

location: <unknown location>:-1

**Comment by prman-pixar** [comment] 2022-09-16 14:59
@deboi238  can you check if the latest commit fixes the problem?

**Comment by deboi238** [comment] 2022-09-16 15:05
I’m using the dev branch

**Comment by prman-pixar** [comment] 2022-09-16 17:18
@deboi238  so it didn't fix the problem?

**Comment by deboi238** [comment] 2022-09-16 22:26
It did fix some of my problem but if it’s multiple texture then it Buggs

**Comment by prman-pixar** [comment] 2022-09-16 22:28
@deboi238 I would need the .blend file and textures if I'm going to fix this.

**Comment by deboi238** [comment] 2022-09-16 22:30
Can you use google drive since one of my model use 58 mb

**Comment by prman-pixar** [comment] 2022-09-16 22:46
@deboi238 Yes, I can use google drive

**Comment by deboi238** [comment] 2022-09-16 23:37
@prman-pixar https://drive.google.com/file/d/1n74dj-UvNVN7i8UCi_lvGhxYPeV-ABD-/view?usp=sharing

**Comment by deboi238** [comment] 2022-09-16 23:37
the .blend is a map that i like to practice my animation

**Comment by prman-pixar** [comment] 2022-09-19 14:37
@deboi238  can you try the latest commit? I'm not confident that it will convert it to something usable, but it should no longer crash.

**Comment by deboi238** [comment] 2022-09-19 14:48
@prman-pixar it dosent crash any more thanks to you, although it still having the same error when converting the textures 
keep saying Error converting *texture*

**Comment by prman-pixar** [comment] 2022-09-19 16:15
@deboi238  what's the error?

**Comment by deboi238** [comment] 2022-09-19 23:35
@prman-pixar it just said Error converting (texture)

**Comment by deboi238** [comment] 2022-09-20 01:10
@prman-pixar new issue too, when i tried to do pxrtexture to output, blender crashes on me

**Comment by deboi238** [comment] 2022-09-20 01:14
@prman-pixar and this too

Python: Traceback (most recent call last):
  File "C:\Users\deboi\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\RenderManForBlender-dev\rman_operators\rman_operators_nodetree.py", line 157, in execute
    elif not rman_cycles_convert.convert_cycles_nodetree(idblock, output):
  File "C:\Users\deboiAppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\RenderManForBlender-dev\rman_cycles_convert\__init__.py", line 272, in convert_cycles_nodetree
    convert_cycles_bsdf(nt, base_surface, begin_cycles_node, 0)
  File "C:\Users\deboi\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\RenderManForBlender-dev\rman_cycles_convert\__init__.py", line 129, in convert_cycles_bsdf
    rman_node = convert_cycles_node(nt, node)
  File "C:\Users\deboi\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\RenderManForBlender-dev\rman_cycles_convert\cycles_convert.py", line 44, in convert_cycles_node
    convert_node_group(nt, node, rman_node)
  File "C:\Users\deboi\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\RenderManForBlender-dev\rman_cycles_convert\cycles_convert.py", line 285, in convert_node_group
    convert_cycles_input(rman_nt, input, rman_output_node, input.name)
  File "C:\Users\deboi\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\RenderManForBlender-dev\rman_cycles_convert\cycles_convert.py", line 180, in convert_cycles_input
    convert_linked_node(nt, socket, rman_node, param_name)
  File "C:\Users\deboi\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\RenderManForBlender-dev\rman_cycles_convert\cycles_convert.py", line 158, in convert_linked_node
    node = convert_cycles_node(nt, socket.links[0].from_node, location)
  File "C:\Users\deboi\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\RenderManForBlender-dev\rman_cycles_convert\cycles_convert.py", line 125, in convert_cycles_node
    node_name = __BL_NODES_MAP__.get(bxdf_name)
NameError: name 'bxdf_name' is not defined

location: <unknown location>:-1

**Comment by prman-pixar** [comment] 2022-09-20 13:51
@deboi238 Can you provide an example .blend file?

**Comment by deboi238** [comment] 2022-09-20 14:22
[my monkey.zip](https://github.com/prman-pixar/RenderManForBlender/files/9608481/my.monkey.zip)

heres one example

**Comment by prman-pixar** [comment] 2022-09-20 16:05
@deboi238  OK, I fixed that error, but there are other errors with that scene. The problem is that you have a shader to RGB node in your shading network(s). RenderMan doesn't have an equivalent node to do that, so your scenes won't convert properly.

As I said from the beginning, it's best to start shading from scratch. This was never guaranteed to work, and the converted networks are not going to be optimal.

**Comment by deboi238** [comment] 2022-09-21 02:00
> @deboi238 OK, I fixed that error, but there are other errors with that scene. The problem is that you have a shader to RGB node in your shading network(s). RenderMan doesn't have an equivalent node to do that, so your scenes won't convert properly.
> 
> As I said from the beginning, it's best to start shading from scratch. This was never guaranteed to work, and the converted networks are not going to be optimal.

thank you

**Closed** 2022-09-21 20:13 UTC
