### ISSUE TITLE
Light Linking Editor improvements

### ISSUE THREAD

**Issue by TzurH** [prman-pixar/RenderManForBlender#624] opened 2021-09-07 12:35 UTC
So... I've been playing around with RfB for around 2 weeks now. It is pretty awesome! But... there are some meh things with it too. And that's mostly the UI/UX.

The current UI/UX of the light linking editor is only fine for scenes with a relatively small amount of objects in. It is impossible to use with scenes containing medium to large amounts of objects. Just have a look at the picture below of a current small-medium scene I'm working on. It would be a terrible time sink having to add all the objects in the scene to the Objects list, let alone set an Illumination rule to all of them - that is because we can't batch process!
![LightLinkingUX](https://user-images.githubusercontent.com/10125645/132340506-08d898b7-2f79-47c0-8d6a-a4d79ed7a681.png)

We need a solution to this problem.
I'm not a programmer. I don't know what it takes to program UI in Blender, or the limitations behind it - maybe there is something that prevents the devs from refining this.
I have come up with a solution that I hope is doable programming-wise, and that is user-friendly and intuitive.
Say we have a scene, and we want to link some objects to a light.
![LightLinkUX_1](https://user-images.githubusercontent.com/10125645/132338570-4fbb4fb3-945f-4db9-bf1a-a7e4a49845fc.png)
Step 1. The user selects the objects he wants to link to a light.
![LightLinkUX_2](https://user-images.githubusercontent.com/10125645/132338580-26a07f66-1e70-4db4-ad92-606af9ca5d90.png)
Step 2. User Shift-select a light, making it the **_Active_** object.
![LightLinkUX_3](https://user-images.githubusercontent.com/10125645/132338721-4e923a10-208c-4f1a-bbd0-214aafd9c5c7.png)
Step 3. Using a right-click sub-menu under Renderman menu the user has a few options to choose from to set the illumination rule:
a. Link selected objects to Active - Default
b. Link selected objects to Active - On
c. Link selected objects to Active - Off
d. Remove from Light Linking
![LightLinkUX_4](https://user-images.githubusercontent.com/10125645/132344120-eda11b89-0233-4a0b-87f9-77657a5c8bc1.png)
If the user wants to remove selected objects from Light Linking altogether, all they have to do is select the objects in the scene, use the right-click menu, and hit the "Remove selected from Light Linking" option.
![LightLinkUX_5](https://user-images.githubusercontent.com/10125645/132344861-0fdbfcb7-0e31-4a3e-af88-2d80cb83fe2a.png)

Again, not a programmer, but I really think that if the above is doable, it would solve a lot of issues with the current UX.
1. Batch processing is now doable - that's awesome! The user can link multiple objects to a light, remove light linking from multiple objects, change the Illumination rule for multiple objects.
2. The user can use Blender's built-in selection tools to select objects in the scene. Be it the Outliner, the viewport, select linked, select by type etc.
3. User friendly and intuitive - can all be done via the viewport if the user wants to. Rarely would need to go into the Light Linking Editor.

Please let me know what you think. Open for feedback from other users too.

**Comment by prman-pixar** [comment] 2021-09-07 15:37
re: the long list of objects

Does the filter search not work for you?

re: using the right click submenu

This should be do-able, as we already do something similar for the light mixer editor. 

The other thing we can add is an invert option.

**Comment by prman-pixar** [comment] 2021-09-07 18:59
Can you see if the latest commit works well for you? This adds the suggestion of adding the light linking operations to the right click menu.

**Comment by TzurH** [comment] 2021-09-08 01:54
> Can you see if the latest commit works well for you? This adds the suggestion of adding the light linking operations to the right click menu.

Unfortunatley, seems like it has messed up Light Linking altogether. I'm unable to set per object rules now. They get overidden globally.
https://user-images.githubusercontent.com/10125645/132432886-27fb0c6f-7d7b-4126-8041-aba078c70fb1.mp4

Also, the "Remove Selected from light_name" function doesn't work.

Still, pretty awesome as a first implementation. I can see this speeding up my workflow tenfolds once working properly. Thank you for your efforts!

**Comment by nuzzar** [comment] 2021-09-08 07:21
In my opinion for light linking and preset browser should have its own dedicated window just like node editor, etc instead of a temporary window like that.

**Comment by TzurH** [comment] 2021-09-08 08:14
I agree with you @nuzzar . But maybe it's not doable or is too much work to program something like that. It's very Blender-specific. I don't know. But anyway, that's why I suggested the right-click menu approach.

**Comment by nuzzar** [comment] 2021-09-08 11:45
Yeah, I know it's probably a lot harder and I'm not sure if it's even possible. But there are other add-on that has its dedicated window. Although it's probably just a duplicate of the node editor.

**Comment by prman-pixar** [comment] 2021-09-08 16:02
@TzurH  can you try the latest commit? We've never had per object per light controls of light linking, so this is somewhat of an invasive change.

Also, I've changed the right click menu a bit. If you have objects selected, but the current active object is not a light, we show the controls for all of the lights in the scene. I don't know how slow this might be if you have a lot of lights in the scene, but it seems useful.

![Screen Shot 2021-09-08 at 8 58 35 AM](https://user-images.githubusercontent.com/7171572/132544081-9db5b1c5-ad14-4687-8fdf-c9b2bf35dcda.png)

re: adding a dedicated window

The only way I know of to do that would be to create your own node tree.  But, I don't know how useful it is to do light linking in a graph like setting.

**Comment by nuzzar** [comment] 2021-09-08 19:35
@prman-pixar I'm not saying to use node tree for light linking. It's pretty obvious it won't be practical. What I mean is a window like these instead of a floating window which are temporary.
![image](https://user-images.githubusercontent.com/18203407/132571400-57fee232-0499-4c9a-86db-0f49e0b1e872.png)

If it's possible to make a custom window like these for light linking that would be great. I'm thinking something like what Maya has. If not or too cumbersome to do, why not do it the blender way and use collection and its link feature for light linking? You could add a light icon to toggle the light link in the outliner.

![image](https://user-images.githubusercontent.com/18203407/132573641-65d3ffa6-47a7-4413-8570-0260bbf2d1e9.png)

**Comment by prman-pixar** [comment] 2021-09-08 21:05
@nuzzar  Right. Like I said I don't know of a way to add a new window like a custom outliner; the only way I know of is to create a custom node tree property.

The collection idea is interesting, but that would break existing scenes. Could be something to consider for the next major version.

**Comment by TzurH** [comment] 2021-09-08 23:49
> We've never had per object per light controls of light linking, so this is somewhat of an invasive change.

Oh my bad. I thought per object light control was a thing, I've only started using the system last week.
I have just opened Houdini for comparison. The way it works in Houdini is you link the objects you ONLY want the light to affect. That actually makes a lot more sense to me too, as you are creating a link between the light and the objects.
![HoudiniLightLink1](https://user-images.githubusercontent.com/10125645/132598774-3cc933ba-7b35-479b-b87f-ae98df6c0148.png)
![HoudiniLightLink2](https://user-images.githubusercontent.com/10125645/132598869-6b81ab5b-5ce9-4474-9709-1ff447580ba8.png)

What is the purpose of having Illumination rules in Blender? I must be misunderstanding something here.
If the rule is Default - it affects the objects in Objects list and everything else in the scene.
If the rule is On - it does the same as above.
Only when the rule is Off for the objects in Objects list - it will not affect the objects.

If you match the behavior of linking In Blender to Houdini, you could remove those rules and only have the 2 buttons for the right-click menu, one for "Link selected to light_name" and one for "Remove selected from light_name". You could then also simplify the Light Linking Editor UI, removing the Illumination column and change the "Objects" column to "Link" so it makes more sense to the user. Have a look at the mockup below.
![BlenderLightLinking1](https://user-images.githubusercontent.com/10125645/132599871-d7b3b2b1-1bf2-454a-aa39-d733b6a85e1e.png)
So in that instance, the light will ONLY affect the Icosphere, or any other objects listed in the "Link" list.

**Comment by TzurH** [comment] 2021-09-09 00:13
> Also, I've changed the right click menu a bit. If you have objects selected, but the current active object is not a light, we show the controls for all of the lights in the scene. I don't know how slow this might be if you have a lot of lights in the scene, but it seems useful.

I don't know if this is a good addition to the right-click menu. My idea behind it is to work in the viewport, so the user has a visual correlation between the objects and the light he has selected (this emphasizes the 'link'). It can bloat the UI if there are many lights in the scene, and if the user hasn't named the lights properly, it can get really confusing and lead to errors. I think the risk of errors is reduced significantly when the user has to select the light and make it active.

An extreme example below, but it can happen.
![BlenderLightLinking2](https://user-images.githubusercontent.com/10125645/132601871-85319338-ab11-44f4-8e98-3dff7d81af91.png)

**Comment by TzurH** [comment] 2021-09-09 00:44
> @TzurH can you try the latest commit? We've never had per object per light controls of light linking, so this is somewhat of an invasive change.

Have just tried it. This works great!!!

Please read my above replies though, especially the one comparing the behaviour of light linking to Houdini - it might solve a lot of headaches and your time. I'm pretty sure the behaviour showcased in Houdini is the same in Maya, as in, the light will ONLY affect objects that are linked to it, but I haven't tested as I don't have Maya, so can't confirm!
I'm deeply sorry for making you work on this prior to comparing how it works in other DCCs, my apologies.

**Comment by prman-pixar** [comment] 2021-09-09 15:38
@TzurH  can you try the latest commit?

I added a pref to invert the light linking behavior. Note, if this is on, it means by default nothing is illuminated. i.e.: if a light is missing from the light linking editor, it does not illuminate anything.

**Comment by TzurH** [comment] 2021-09-09 23:23
Hmm, doesn't seem to work for me.
![image](https://user-images.githubusercontent.com/10125645/132774844-a52379d7-1396-4883-aecd-18684170d7ac.png)
![image](https://user-images.githubusercontent.com/10125645/132775059-6a8cd16c-89a6-4a72-b26b-3f2d7845b615.png)

**Comment by prman-pixar** [comment] 2021-09-10 15:44
@TzurH  Can you try this scene? 
[cornell_box_lpe.zip](https://github.com/prman-pixar/RenderManForBlender/files/7144907/cornell_box_lpe.zip)

It works when I do:

1. Start IPR
2. Select Suzanne, then select the PxrRectLight
3. Right click RenderMan->Light Linking->Link Selected to PxrRectLight

**Comment by TzurH** [comment] 2021-09-11 01:10
@prman-pixar Tested your scene, works well.
I've noticed you have 2 lights in your scene so I've tested a bit more. A bunch of issues:

1. If you only have 1 light linked to a few objects, it won't work - it illuminates everything in the scene, which is what I reported before:
![image](https://user-images.githubusercontent.com/10125645/132930632-b8c29c9c-c4e5-4da4-bad5-0d2ef1560d50.png)
In Houdini - Red light has no links set:
![image](https://user-images.githubusercontent.com/10125645/132931225-eefa8c08-150d-409e-a9ef-c134b8c8106a.png)
Red light is linked to Monkey only:
![image](https://user-images.githubusercontent.com/10125645/132931249-14113a42-206f-4244-a742-2aff0890d728.png)

2. If you have more than 1 light of the same type, only one of them will illuminate the scene:
![image](https://user-images.githubusercontent.com/10125645/132930266-5798454b-fdd4-4492-b9b1-f352f627a337.png)
![image](https://user-images.githubusercontent.com/10125645/132930325-e1a8acc0-6fff-4359-9f71-abb4958bd4eb.png)

3. In case you have 2 of the same lights, and you remove the one that was illuminating the scene, now the other one isn't, looks like this bug is connected to the one reported at 2.
![image](https://user-images.githubusercontent.com/10125645/132930492-30be4896-78f4-405d-a938-3bebfc09a0fc.png)

4. If you have 2 lights of a different type, and one of them is linked to a few objects, the other light won't illuminate those objects. They now **_only_** receive light from the light that they are linked to. They should still be illuminated from the other lights in the scene if those lights have no links set to them, as they are suppose to illuminate everything in the scene.
![image](https://user-images.githubusercontent.com/10125645/132931045-37ad827c-cc9f-423b-9bbc-ca0b151367c2.png)
Here it is in Houdini:
![image](https://user-images.githubusercontent.com/10125645/132931158-e9f4aa9c-4d2f-415b-a927-65a9e218cb88.png)

** I've removed GI so it's clear to see what's happening in the pics.
I hope my writing is clear enough to understand. It's hard writing with a mouse haha.

**Comment by prman-pixar** [comment] 2021-09-13 18:51
@TzurH  can you try the latest commit. It should work with one light and objects should now include lights that are not linked.

**Comment by TzurH** [comment] 2021-09-14 03:54
@prman-pixar all reported issues have been fixed!
I didn't stumble upon any bugs as of yet while testing the invert light linking behaviour - so I think you can close this issue.

thanks for your work on this 💯 👍 
I'm very pleased with how the new system works. both the invert light linking and the non invert. the added option to set per object rules for example could become very useful for artists using the default light linking behaviour. personally, I prefer the invert light linking behaviour so I'm going to stick with that! :]

**Comment by prman-pixar** [comment] 2021-09-14 14:02
Great! I'll consider this close then.

**Closed by prman-pixar** 2021-09-14 14:02 UTC
