### ISSUE TITLE
Area Light SizeY value

### ISSUE THREAD

**Issue by AndreasReschGFX** [prman-pixar/RenderManForBlender#533] opened 2017-08-08 17:33 UTC
Hello.

The SizeY value of an area light is ignored and only the SizeX value is used. So the lights are always square.

Here's an example scene ... [http://www.andreasresch.at/upload/Renderman_Test_115.zip](url)

Cheers,
Andreas

**Comment by jdent02** [comment] 2017-08-10 03:53
https://github.com/prman-pixar/RenderManForBlender/commit/bdf4ef45667279cd863cb405ff033b469bc7beeb

This is the commit that broke the 'SizeY' slider.  I'm playing around with trying to fix it but if anyone else knows how to fix it by all means.......

**Comment by jdent02** [comment] 2017-08-10 03:59
In the meantime use scaling on the light (and leave the sliders at 1).  That seems to work and produce the correct shape.

**Comment by jdent02** [comment] 2017-08-10 04:06
Note: The size sliders for the disk light are producing odd results as well.  Only solution is to set the slider at 1 and use object scaling to set the light size.

**Comment by bsavery** [comment] 2017-08-10 05:27
Change line 662 to use size_y

**Comment by AndreasReschGFX** [comment] 2017-08-10 05:27
Hi,

I know that using the size work, but it still has to be labeled as a bug. Other users might get confused.

**Comment by jdent02** [comment] 2017-08-10 13:25
I did change that line but it lead to some incorrect light shapes (corners shaved off, trapezoidal shapes)

**Comment by jdent02** [comment] 2017-08-11 16:24
Here's an example of what happens when I make that change to 662:
![blender](https://user-images.githubusercontent.com/13521172/29222240-4cb5362e-7e87-11e7-91d3-04fbf1149330.PNG)
This is the blender settings
![render](https://user-images.githubusercontent.com/13521172/29222241-4cb87384-7e87-11e7-9aeb-a14ea96c4b8f.PNG)
Here is the render

Also I've noticed that the size slider does not work correctly with sphere lights either.  Changing the size to 8 produces a much smaller lamp than the 3D display in the render.  Leaving the slider at 1 and scaling in the viewport gives correct results.

**Comment by jdent02** [comment] 2017-08-11 16:26
I'm pretty much clueless when it comes to manipulating matrices so I'm not sure if I can properly fix this one other than reverting to the previous code (which had some glitches when scaling but the sliders worked correctly).

**Comment by AndreasReschGFX** [comment] 2017-08-11 16:32
The Disk and Sphere sizes look correct to me - the label should say "Diameter" though instead of "Radius".

**Comment by jdent02** [comment] 2017-08-11 16:50
I was saying the sliders produce incorrect results when changing line 662 to reflect size_y instead of just size.

**Comment by jdent02** [comment] 2017-08-11 16:51
Without making that change the sliders work fine except for the area 'Y' dimension.

**Comment by a-e-k** [comment] 2017-08-20 09:10
Hi @jdent02,

The change that I just checked in a few minutes ago appears to fix this issue for me.  It's pretty much @bsavery's proposed fix with a couple of other minor bits.  I've been unable to reproduce the shaved off corners or trapezoidal shapes that you mentioned.  Could you please test my change and see if you still see that?  If you do, could you provide me with any more detail about how got there or a repro case?  I suspect that it's unrelated to the current issue but it would still be good to find out what caused that clipping.

Thanks,
\- Andrew

**Comment by AndreasReschGFX** [comment] 2017-08-20 09:29
Hooray,

works for me. I changes the lines in the latest master branch manually instead of using your branch though. No cut corners either.

Cheers,
Andreas

**Comment by jdent02** [comment] 2017-08-20 18:33
I'm still seeing the issue when directly downloading the addon from your repo.

default render:
![1x1 no scale render](https://user-images.githubusercontent.com/13521172/29497348-ea3ffc8c-85ab-11e7-849a-c2c9133839ad.PNG)

Blender settings:
![1x1 no scale](https://user-images.githubusercontent.com/13521172/29497349-ea4270ac-85ab-11e7-819e-d77f331e6223.PNG)

Scaling the light along the X axis:
![1x1 with 3x scale render](https://user-images.githubusercontent.com/13521172/29497350-ea439090-85ab-11e7-8db7-dd1a94346fd2.PNG)

Blender scene:
![1x1 with 3x scale](https://user-images.githubusercontent.com/13521172/29497351-ea44e6c0-85ab-11e7-9f35-c23331561f97.PNG)

Changing light size (no scaling):
![3x1 no scale render](https://user-images.githubusercontent.com/13521172/29497352-ea4673b4-85ab-11e7-944d-d19d3819256c.PNG)

Blender scene:
![3x1 no scale](https://user-images.githubusercontent.com/13521172/29497353-ea4e11b4-85ab-11e7-88e0-6bb49e979595.PNG)

Here's my test file:

[untitled.zip](https://github.com/prman-pixar/RenderManForBlender/files/1237269/untitled.zip)

**Comment by AndreasReschGFX** [comment] 2017-08-21 06:34
I can confirm that. I only tried the light when it had no rotation applied to it. In that case it works. As soon as you rotate the light, the weirdness happens.

Cheers,
Andreas

**Comment by a-e-k** [comment] 2017-08-22 06:40
Confirmed.  Thanks for the repro case.

Yes, the problem here is that multiplying the first three entries along the diagonal in order to produce a scaling is only valid if there is no rotation involved.  That is, the off-diagonal entries in the upper-left 3x3 part of the matrix must all be zero.  Once there's a rotation those entries are non-zero and just multiplying the diagonal entries makes the matrix non-orthogonal which RenderMan doesn't like for lights.  This explains Andreas' observation that rotation is the key.

So as near as I can tell, it looks like the old code was actually more correct here.  The main thing that I can see is that it did not create correct scaling transforms for disk lights, and it allowed non-uniform scalings from the properties panel to pass through on sphere lights.  I've revised my commit to try to address all these issues.

I'll ask you to bear with me here as I get acclimated, by the way.  I'm fairly new to git, GitHub, and Blender.  But I've been having fun learning Blender and tinkering with this addon in my spare time.  I feel like Blender has finally been starting to click for me this time around as I push myself to use it more.

Thanks,
- Andrew

**Comment by AndreasReschGFX** [comment] 2017-08-22 07:05
Hey Andrew,

it looks good now. I tried rotations in all directions and the shape stays intact. Great job. Again, I changed the code in the recent master instead of using your code base. So that should be fine.

Thanks,
Andreas

**Comment by jdent02** [comment] 2017-08-22 13:06
Thanks a-e-k.  Like I said I'm a complete loss when it comes to manipulating matrixes and geometry so I wasn't able to figure out what was going on.

BTW personal question:  Are you a Pixar guy too?  You seem a lot more knowledgeable than the rest of us :)

**Closed** 2017-08-22 16:37 UTC

**Comment by a-e-k** [comment] 2017-08-22 16:56
Yep!  I've been a member of the core RenderMan development team for almost eight years now.  So I'm pretty well acquainted with the RenderMan internals, plus the rendering theory and math side of things.  As I'd said, it's git, GitHub, and Blender that I'm still quite new to.  So it's very likely that I may ask for help on that front as I get up to speed.  But I've been having fun using Blender the last few weeks when I need to put together a quick test scene -- it's so snappy!  So that's what's led me to start contributing.  Unfortunately, I don't have a huge amount of time to contribute but I'm hoping to start doing more when I can.

**Comment by jdent02** [comment] 2017-08-22 18:36
Yeah the raw math is what trips me up.  I understand the conceptual theory but I haven't got the knowledge to join the two yet.....

Really cool to have you contributing.  If there is anything I can do to help just give a shout.
