### ISSUE TITLE
Fluid translation

### ISSUE THREAD

**Issue by cedricp** [prman-pixar/RenderManForBlender#620] opened 2021-08-20 09:42 UTC
Hi,
I attached a patch for fluid export that did not work for me. It looks OK now, but I can't understand how to set the PxrVolume correctly to get _flame_ and _density_ color.

As a side note, **OpenVDB** volume instantly crashes Blender (PrMan crash) on Linux (tested with bunny_cloud.vdb)
Here's the call stack : 
```
#0  0x0000000001348789 in ?? ()
#1  0x000000000a73c19d in std::locale::_Impl::~_Impl() ()
#2  0x000000000a73c356 in std::locale::~locale() ()
#3  0x00007fffefbb8058 in std::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> >::~basic_ostringstream() ()
   from /lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007fff174dff2a in ?? ()
   from /opt/pixar/RenderManProServer-24.1/lib/plugins/impl_openvdb.so
#5  0x00007fff174d1a71 in ?? ()
   from /opt/pixar/RenderManProServer-24.1/lib/plugins/impl_openvdb.so
#6  0x00007fff171ece9b in ImplicitFieldNew ()
   from /opt/pixar/RenderManProServer-24.1/lib/plugins/impl_openvdb.so
#7  0x00007fffc892e9f5 in ?? ()
   from /opt/pixar/RenderManProServer-24.1/lib/libprman.so
#8  0x00007fffc8b99543 in ?? ()
   from /opt/pixar/RenderManProServer-24.1/lib/libprman.so
#9  0x00007fffc8b9b4f0 in ?? ()
   from /opt/pixar/RenderManProServer-24.1/lib/libprman.so
#10 0x00007fffc82d775d in ?? ()
```

[fluid.zip](https://github.com/prman-pixar/RenderManForBlender/files/7020603/fluid.zip)

**Comment by prman-pixar** [comment] 2021-08-23 23:26
Thanks for the patch. I've committed it to the repo. However, I can't reproduce the crash on linux. Is it only happening on linux for you?

**Comment by cedricp** [comment] 2021-08-24 07:39
My bad, as I use Ubuntu, the libstdc++ was not the good one ! It's fixed by linking against CentOS libs

**Closed** 2021-08-24 07:58 UTC
